SELECT NOM, PRENOM, TITRE, PRET.CODE_BARRE, DATE_EMP, DATE_RETOUR  FROM ADHERENT, PRET, LIVRE, OEUVRE  WHERE ADHERENT.Numero_ADHERENT = PRET.Numero_ADHERENT AND LIVRE.COTE = OEUVRE.COTE AND LIVRE.CODE_BARRE = PRET.CODE_BARRE;

SELECT ISBN, DISPONIBILITE, DATE_ACHAT, LIVRE.COTE, CODE_BARRE, TITRE, DATE_FORMAT(DATE_PARUTION , '%d-%m-%Y') DATE_PARUTION , NOM_AUTEUR, PRENOM_AUTEUR, NOM_EDI, DATE_FORMAT(DATE_ACHAT , '%d-%m-%Y') DATE_ACHAT FROM LIVRE, OEUVRE, AUTEUR, REDIGER,EDITEUR  WHERE LIVRE.COTE = OEUVRE.COTE AND LIVRE.COTE = REDIGER.COTE AND AUTEUR.ID_AUTEUR = REDIGER.ID_AUTEUR AND LIVRE.ID_EDITEUR = EDITEUR.ID_EDITEUR;

SELECT ISBN, LIVRE.COTE, CODE_BARRE, TITRE, DATE_FORMAT(DATE_PARUTION , '%d-%m-%Y') DATE_PARUTION , NOM_AUTEUR, PRENOM_AUTEUR, NOM_EDI  FROM LIVRE, OEUVRE, AUTEUR, REDIGER,EDITEUR  WHERE LIVRE.COTE = OEUVRE.COTE AND LIVRE.COTE = REDIGER.COTE AND AUTEUR.ID_AUTEUR = REDIGER.ID_AUTEUR AND LIVRE.ID_EDITEUR = EDITEUR.ID_EDITEUR and ISBN="00003";

SELECT NOM, PRENOM, DATE_EMP, DATE_RETOUR, PROLONGATION,TITRE, NUMERO_EXEMPLAIRE  FROM ADHERENT, PRET, LIVRE, OEUVRE WHERE LIVRE.COTE=OEUVRE.COTE AND PRET.CODE_BARRE = LIVRE.CODE_BARRE AND ADHERENT.Numero_ADHERENT= PRET.Numero_ADHERENT;

UPDATE LIVRE SET  DISPONIBILITE =  '0' WHERE  CODE_BARRE =  '00002';

INSERT INTO PRET (Numero_ADHERENT, CODE_BARRE, DATE_EMP, DATE_RETOUR, Prolongation) VALUES ('81858', '11111111147', '2014-04-08', '2014-04-16', '0');

SELECT * FROM PRET,LIVRE HAVING  Numero_ADHERENT=85213 AND LIVRE.CODE_BARRE=PRET.CODE_BARRE AND  PRET.CODE_BARRE=00002 AND DISPONIBILITE=0  ORDER BY DATE_RETOUR DESC LIMIT 1  ;

SELECT * FROM ADHERENT HAVING NOM  like "R%"  ORDER BY NOM ASC;

SELECT * FROM CARACTERISE, MOT_CLE WHERE CARACTERISE.NUM_MOTCLE=MOT_CLE.NUM_MOTCLE;
=======
SELECT * FROM CARACTERISE, MOT_CLE, LIVRE  WHERE CARACTERISE.NUM_MOTCLE=MOT_CLE.NUM_MOTCLE AND LIVRE.COTE=CARACTERISE.COTE AND MOT_CLES='UTOPIE';

SELECT ISBN, DISPONIBILITE, DATE_ACHAT, LIVRE.COTE, CODE_BARRE, TITRE,  DATE_FORMAT(DATE_PARUTION , '%d-%m-%Y') DATE_PARUTION , NOM_AUTEUR, PRENOM_AUTEUR, NOM_EDI, DATE_FORMAT(DATE_ACHAT , '%d-%m-%Y') DATE_ACHAT, NUMERO_EXEMPLAIRE  FROM LIVRE, OEUVRE, AUTEUR, REDIGER,EDITEUR,CARACTERISE, MOT_CLE WHERE LIVRE.COTE = OEUVRE.COTE AND LIVRE.COTE = REDIGER.COTE  AND AUTEUR.ID_AUTEUR = REDIGER.ID_AUTEUR  AND LIVRE.ID_EDITEUR = EDITEUR.ID_EDITEUR AND CARACTERISE.NUM_MOTCLE=MOT_CLE.NUM_MOTCLE AND LIVRE.COTE=CARACTERISE.COTE AND MOT_CLES='UTOPIE'

SELECT ISBN, DISPONIBILITE, DATE_ACHAT, LIVRE.COTE, CODE_BARRE, TITRE,  DATE_FORMAT(DATE_PARUTION , '%d-%m-%Y') DATE_PARUTION , NOM_AUTEUR, PRENOM_AUTEUR, NOM_EDI, DATE_FORMAT(DATE_ACHAT , '%d-%m-%Y') DATE_ACHAT, NUMERO_EXEMPLAIRE  FROM LIVRE, OEUVRE, AUTEUR, REDIGER,EDITEUR,CARACTERISE, MOT_CLE WHERE LIVRE.COTE = OEUVRE.COTE AND LIVRE.COTE = REDIGER.COTE  AND AUTEUR.ID_AUTEUR = REDIGER.ID_AUTEUR  AND LIVRE.ID_EDITEUR = EDITEUR.ID_EDITEUR AND CARACTERISE.NUM_MOTCLE=MOT_CLE.NUM_MOTCLE AND LIVRE.COTE=CARACTERISE.COTE AND  AND ISBN=?


INSERT INTO `bibliotheque`.`EDITEUR` (`ID_Editeur`, `NOM_EDI`) VALUES ('78475', 'Dupuis');

 SELECT * FROM LIVRE, PRET HAVING LIVRE.CODE_BARRE=PRET.CODE_BARRE  AND  DATE(NOW()) > DATE_RETOUR  AND DISPONIBILITE=0  ;

 SELECT * FROM LIVRE, PRET WHERE LIVRE.CODE_BARRE=PRET.CODE_BARRE  AND  DATE(NOW()) > DATE_RETOUR  AND DISPONIBILITE=0  ;

Verifier pret disponibilité = 0;

UPDATE  `bibliotheque`.`ADHERENT` SET  `NOM` =  'MDJASSIRI1',
`PRENOM` =  'AMIRDINE1',
`VILLE` =  'Toulon1',
`SEXE` =  'Masculin1',
`ADRESSE` =  '1 rue de la busserine1',
`COURRIEL` =  'mdjassiri.amridine@yahoo.fr1' WHERE  `ADHERENT`.`Numero_ADHERENT` =  '81858';

SELECT * FROM RESERVE, LIVRE WHERE LIVRE.COTE=RESERVE.COTE;

 SELECT r.NOM, PRENOM, TITRE, t.CODE_BARRE, DATE_FORMAT(r.DATE_EMP,'%d-%m-%Y') DATE_EMP, t.DATE_RETOUR FROM (SELECT PRET.NUMERO_ADHERENT,NOM, PRENOM,TITRE, PRET.CODE_BARRE, MAX(DATE_EMP) as DATE_EMP, DATE_RETOUR FROM PRET,ADHERENT,LIVRE, OEUVRE  WHERE PRET.NUMERO_ADHERENT = ADHERENT.NUMERO_ADHERENT AND PRET.CODE_BARRE = LIVRE.CODE_BARRE AND  LIVRE.COTE=OEUVRE.COTE AND DISPONIBILITE=0  GROUP BY CODE_BARRE) r INNER JOIN PRET t ON t.CODE_BARRE = r.CODE_BARRE AND t.DATE_EMP = r.DATE_EMP AND t.NUMERO_ADHERENT=85213;

